// صفحة جدول الرحلة اليومي — أيام وأنشطة CRUD كامل + ربط بالأماكن المحفوظة + إعادة ترتيب + فلترة حقيقية

let itineraryPeriodFilter = 'الكل';

function todayStr() {
  const d = new Date();
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;
}

function activityPeriod(time) {
  if (!time) return null;
  const hour = Number(time.split(':')[0]);
  if (hour < 12) return 'صباح';
  if (hour < 17) return 'ظهر';
  return 'مساء';
}

// إنشاء أيام الرحلة تلقائيًا حسب تواريخ الرحلة، مرة واحدة فقط إذا لم توجد أي أيام بعد
function autoGenerateDays(trip) {
  if (!trip.startDate || !trip.endDate) return false;
  if (store.list('days').length > 0) return false;
  const start = new Date(trip.startDate + 'T00:00:00');
  const end = new Date(trip.endDate + 'T00:00:00');
  if (isNaN(start.getTime()) || isNaN(end.getTime()) || end < start) return false;
  const diffDays = Math.round((end - start) / 86400000) + 1;
  if (diffDays > 60) return false;
  for (let d = new Date(start); d <= end; d.setDate(d.getDate() + 1)) {
    const dateStr = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;
    store.add('days', { date: dateStr, title: '', notes: '' });
  }
  return true;
}

// ---------- نموذج اليوم ----------
function dayFormHtml(day) {
  const d = day || {};
  const trip = store.getTrip();
  return `
    <form id="day-form" class="flex-col gap-3">
      <div class="field">
        <label>التاريخ</label>
        <input type="date" name="date" required value="${escapeHtml(d.date || trip.startDate || '')}" />
      </div>
      <div class="field">
        <label>عنوان اليوم (اختياري)</label>
        <input type="text" name="title" placeholder="مثال: يوم استكشاف وسط المدينة" value="${escapeHtml(d.title || '')}" />
      </div>
      <div class="field">
        <label>ملاحظات (اختياري)</label>
        <textarea name="notes" placeholder="أي تفاصيل عامة عن اليوم...">${escapeHtml(d.notes || '')}</textarea>
      </div>
      <div class="modal-actions">
        <button type="submit" class="btn btn-primary btn-block">${icon('check', 16)}<span>${day ? 'حفظ التعديلات' : 'إضافة اليوم'}</span></button>
      </div>
    </form>`;
}

function openDayModal(container, dayId) {
  const day = dayId ? store.get('days', dayId) : null;
  openModal(day ? 'تعديل اليوم' : 'إضافة يوم', dayFormHtml(day), () => {
    qs('#day-form').addEventListener('submit', (e) => {
      e.preventDefault();
      const fd = new FormData(e.target);
      const data = { date: fd.get('date'), title: fd.get('title').trim(), notes: fd.get('notes').trim() };
      if (!data.date) return;
      if (day) {
        store.update('days', day.id, data);
        toast('تم تحديث اليوم', 'success');
      } else {
        store.add('days', data);
        toast('تمت إضافة اليوم', 'success');
      }
      closeModal();
      renderItinerary(container);
    });
  });
}

// ---------- نموذج النشاط ----------
function activityFormHtml(activity) {
  const a = activity || {};
  const places = store.list('places');
  return `
    <form id="activity-form" class="flex-col gap-3">
      ${places.length ? `
      <div class="field">
        <label>اختر من أماكنك المحفوظة (اختياري)</label>
        <select name="placeId" id="activity-place-select">
          <option value="">بدون ربط — إدخال يدوي</option>
          ${places.map((p) => `<option value="${p.id}" ${a.placeId === p.id ? 'selected' : ''}>${escapeHtml(p.name)}${p.city ? ' — ' + escapeHtml(p.city) : ''}</option>`).join('')}
        </select>
      </div>` : ''}
      <div class="field">
        <label>اسم المكان أو النشاط</label>
        <input type="text" name="title" required placeholder="مثال: زيارة آيا صوفيا" value="${escapeHtml(a.title || '')}" />
      </div>
      <div class="field-row">
        <div class="field">
          <label>الوقت (اختياري)</label>
          <input type="time" name="time" value="${escapeHtml(a.time || '')}" />
        </div>
        <div class="field">
          <label>نوع النشاط</label>
          <select name="type">
            ${PLACE_TYPES.map((t) => `<option value="${t.id}" ${a.type === t.id ? 'selected' : ''}>${t.label}</option>`).join('')}
          </select>
        </div>
      </div>
      <div class="field" id="activity-mapsurl-field" ${a.placeId ? 'hidden' : ''}>
        <label>رابط Google Maps (اختياري)</label>
        <input type="text" name="mapsUrl" placeholder="الصق رابط الموقع من خرائط جوجل" value="${escapeHtml(a.mapsUrl || '')}" />
      </div>
      <div class="field">
        <label>التكلفة التقديرية (اختياري)</label>
        <input type="number" name="cost" min="0" value="${escapeHtml(a.cost || '')}" />
      </div>
      <div class="field">
        <label>ملاحظات (اختياري)</label>
        <textarea name="notes" placeholder="تفاصيل إضافية...">${escapeHtml(a.notes || '')}</textarea>
      </div>
      <div class="modal-actions">
        <button type="submit" class="btn btn-primary btn-block">${icon('check', 16)}<span>${activity ? 'حفظ التعديلات' : 'إضافة النشاط'}</span></button>
      </div>
    </form>`;
}

function openActivityModal(container, dayId, activityId) {
  const activity = activityId ? store.get('activities', activityId) : null;
  openModal(activity ? 'تعديل النشاط' : 'إضافة نشاط', activityFormHtml(activity), () => {
    const form = qs('#activity-form');
    const placeSelect = qs('#activity-place-select');
    const mapsField = qs('#activity-mapsurl-field');

    if (placeSelect) {
      placeSelect.addEventListener('change', (e) => {
        const placeId = e.target.value;
        if (placeId) {
          const p = store.get('places', placeId);
          if (p) {
            form.querySelector('[name=title]').value = p.name;
            form.querySelector('[name=type]').value = p.type || 'other';
          }
          mapsField.hidden = true;
        } else {
          mapsField.hidden = false;
        }
      });
    }

    form.addEventListener('submit', (e) => {
      e.preventDefault();
      const fd = new FormData(form);
      const placeId = fd.get('placeId') || '';
      const mapsUrlRaw = placeId ? '' : fd.get('mapsUrl').trim();
      if (mapsUrlRaw && !isValidMapsUrl(mapsUrlRaw)) {
        toast('الرابط المُدخل ليس رابط Google Maps صالحًا', 'error');
        return;
      }
      const data = {
        title: fd.get('title').trim(),
        time: fd.get('time'),
        type: fd.get('type'),
        placeId: placeId || '',
        mapsUrl: mapsUrlRaw,
        cost: fd.get('cost'),
        notes: fd.get('notes').trim(),
      };
      if (!data.title) return;
      if (activity) {
        store.update('activities', activity.id, data);
        toast('تم تحديث النشاط', 'success');
      } else {
        const dayActivities = store.list('activities').filter((a) => a.dayId === dayId);
        const maxOrder = dayActivities.reduce((m, a) => Math.max(m, a.order ?? 0), -1);
        store.add('activities', { ...data, dayId, order: maxOrder + 1 });
        toast('تمت إضافة النشاط', 'success');
      }
      closeModal();
      renderItinerary(container);
    });
  });
}

function activityMapsInfo(a) {
  const trip = store.getTrip();
  if (a.placeId) {
    const p = store.get('places', a.placeId);
    if (p) return p.mapsUrl || mapsSearchUrl([p.name, p.city, p.country].filter(Boolean).join(' '));
  }
  if (a.mapsUrl) return a.mapsUrl;
  if (a.title) return mapsSearchUrl([a.title, trip.city, trip.country].filter(Boolean).join(' '));
  return null;
}

function moveActivity(dayId, activityId, direction) {
  const acts = store.list('activities').filter((a) => a.dayId === dayId).sort((a, b) => (a.order ?? 0) - (b.order ?? 0));
  const idx = acts.findIndex((a) => a.id === activityId);
  const swapIdx = direction === 'up' ? idx - 1 : idx + 1;
  if (idx === -1 || swapIdx < 0 || swapIdx >= acts.length) return;
  const a1 = acts[idx];
  const a2 = acts[swapIdx];
  const o1 = a1.order ?? idx;
  const o2 = a2.order ?? swapIdx;
  store.update('activities', a1.id, { order: o2 });
  store.update('activities', a2.id, { order: o1 });
}

function activityItemHtml(a, isFirst, isLast, allowReorder) {
  const typeMeta = PLACE_TYPES.find((t) => t.id === a.type) || PLACE_TYPES[PLACE_TYPES.length - 1];
  const mapsUrl = activityMapsInfo(a);
  return `
    <div class="item-card" data-activity-id="${a.id}" style="padding:10px;">
      <div class="page-header-icon" style="width:30px;height:30px;border-radius:9px;">${icon(typeMeta.icon, 14)}</div>
      <div style="flex:1; min-width:0;">
        <div class="item-title" style="font-size:13.5px;">${escapeHtml(a.title)}</div>
        <div class="item-meta">
          ${a.time ? `<span class="badge badge-primary">${escapeHtml(a.time)}</span>` : ''}
          <span class="badge">${escapeHtml(typeMeta.label)}</span>
          ${a.cost ? `<span class="badge badge-accent">${money(a.cost)}</span>` : ''}
        </div>
        ${a.notes ? `<div class="text-sm text-muted mt-1">${escapeHtml(a.notes)}</div>` : ''}
        ${mapsUrl ? `<a class="btn btn-outline btn-sm mt-2" href="${escapeHtml(mapsUrl)}" target="_blank" rel="noopener noreferrer">${icon('map', 13)}<span>فتح على الخريطة</span></a>` : ''}
      </div>
      <div class="item-actions" style="flex-direction:column; align-items:stretch;">
        <div class="flex gap-1">
          <button class="icon-btn btn-sm" style="width:28px;height:28px;" data-activity-action="edit" aria-label="تعديل">${icon('edit', 12)}</button>
          <button class="icon-btn btn-sm" style="width:28px;height:28px;" data-activity-action="delete" aria-label="حذف">${icon('trash', 12)}</button>
        </div>
        ${allowReorder ? `
        <div class="flex gap-1 mt-1">
          <button class="icon-btn btn-sm" style="width:28px;height:28px;" data-activity-action="move-up" ${isFirst ? 'disabled' : ''} aria-label="نقل لأعلى">${icon('chevronUp', 13)}</button>
          <button class="icon-btn btn-sm" style="width:28px;height:28px;" data-activity-action="move-down" ${isLast ? 'disabled' : ''} aria-label="نقل لأسفل">${icon('chevronDown', 13)}</button>
        </div>` : ''}
      </div>
    </div>`;
}

function dayCardHtml(day, activities, allowReorder) {
  const isToday = day.date === todayStr();
  return `
    <div class="card mt-2" data-day-id="${day.id}">
      <div class="flex items-center justify-between">
        <div>
          <div class="flex items-center gap-2">
            <span class="font-bold">${formatDateAr(day.date)}</span>
            ${isToday ? '<span class="badge badge-success">اليوم</span>' : ''}
          </div>
          ${day.title ? `<div class="text-sm text-muted mt-1">${escapeHtml(day.title)}</div>` : ''}
        </div>
        <div class="item-actions">
          <button class="icon-btn btn-sm" style="width:32px;height:32px;" data-day-action="add-activity" aria-label="إضافة نشاط">${icon('plus', 15)}</button>
          <button class="icon-btn btn-sm" style="width:32px;height:32px;" data-day-action="edit" aria-label="تعديل اليوم">${icon('edit', 14)}</button>
          <button class="icon-btn btn-sm" style="width:32px;height:32px;" data-day-action="delete" aria-label="حذف اليوم">${icon('trash', 14)}</button>
        </div>
      </div>
      ${day.notes ? `<div class="text-sm text-muted mt-2">${escapeHtml(day.notes)}</div>` : ''}
      <div class="mt-3">
        ${activities.length ? activities.map((a, i) => activityItemHtml(a, i === 0, i === activities.length - 1, allowReorder)).join('') : `<div class="text-sm text-muted" style="text-align:center; padding:10px;">لا توجد أنشطة في هذا اليوم${itineraryPeriodFilter !== 'الكل' ? ' لهذه الفترة' : ''}</div>`}
      </div>
    </div>`;
}

function renderItinerary(container) {
  const trip = store.getTrip();
  autoGenerateDays(trip);

  const allDays = store.list('days').slice().sort((a, b) => (a.date > b.date ? 1 : -1));
  const allActivities = store.list('activities');
  const allowReorder = itineraryPeriodFilter === 'الكل';

  let days = allDays;
  if (itineraryPeriodFilter === 'اليوم الحالي') {
    days = allDays.filter((d) => d.date === todayStr());
  }

  const filters = `
    <div class="chip-row mt-2">
      <button class="chip ${itineraryPeriodFilter === 'الكل' ? 'active' : ''}" data-period="الكل">كل الأيام</button>
      <button class="chip ${itineraryPeriodFilter === 'اليوم الحالي' ? 'active' : ''}" data-period="اليوم الحالي">اليوم الحالي</button>
      <button class="chip ${itineraryPeriodFilter === 'صباح' ? 'active' : ''}" data-period="صباح">صباح</button>
      <button class="chip ${itineraryPeriodFilter === 'ظهر' ? 'active' : ''}" data-period="ظهر">ظهر</button>
      <button class="chip ${itineraryPeriodFilter === 'مساء' ? 'active' : ''}" data-period="مساء">مساء</button>
    </div>`;

  const daysHtml = days.map((day) => {
    let activities = allActivities.filter((a) => a.dayId === day.id).sort((a, b) => (a.order ?? 0) - (b.order ?? 0));
    if (['صباح', 'ظهر', 'مساء'].includes(itineraryPeriodFilter)) {
      activities = activities.filter((a) => activityPeriod(a.time) === itineraryPeriodFilter);
    }
    return dayCardHtml(day, activities, allowReorder);
  }).join('');

  container.innerHTML = `
    ${pageHeader({
      title: 'جدول الرحلة اليومي',
      desc: trip.startDate ? `من ${formatDateAr(trip.startDate)} إلى ${formatDateAr(trip.endDate) || '—'}` : 'خطط لكل يوم من رحلتك بالتفصيل',
      iconName: 'calendar',
      actions: `<button class="btn btn-primary btn-sm" id="add-day-btn">${icon('plus', 16)}<span>إضافة يوم</span></button>`,
    })}
    ${filters}
    <div id="days-list">
      ${days.length ? daysHtml : emptyState(
        allDays.length
          ? { iconName: 'calendar', title: 'لا يوجد يوم مطابق', desc: 'لا يوجد يوم بتاريخ اليوم ضمن الأيام المضافة.' }
          : { iconName: 'calendar', title: 'لا يوجد جدول بعد', desc: 'أضف تواريخ رحلتك في صفحة بيانات الرحلة لإنشاء الأيام تلقائيًا، أو أضف يومًا يدويًا.' }
      )}
    </div>
  `;

  qs('#add-day-btn').addEventListener('click', () => openDayModal(container));

  qsa('[data-period]').forEach((btn) => {
    btn.addEventListener('click', () => { itineraryPeriodFilter = btn.dataset.period; renderItinerary(container); });
  });

  qs('#days-list').addEventListener('click', (e) => {
    const dayEl = e.target.closest('[data-day-id]');
    if (!dayEl) return;
    const dayId = dayEl.dataset.dayId;

    const dayAction = e.target.closest('[data-day-action]')?.dataset.dayAction;
    if (dayAction === 'add-activity') {
      openActivityModal(container, dayId);
      return;
    }
    if (dayAction === 'edit') {
      openDayModal(container, dayId);
      return;
    }
    if (dayAction === 'delete') {
      if (confirm('سيؤدي هذا لحذف اليوم وكل أنشطته. هل تريد المتابعة؟')) {
        store.list('activities').filter((a) => a.dayId === dayId).forEach((a) => store.remove('activities', a.id));
        store.remove('days', dayId);
        toast('تم حذف اليوم');
        renderItinerary(container);
      }
      return;
    }

    const activityEl = e.target.closest('[data-activity-id]');
    if (!activityEl) return;
    const activityId = activityEl.dataset.activityId;
    const activityAction = e.target.closest('[data-activity-action]')?.dataset.activityAction;
    if (activityAction === 'edit') {
      openActivityModal(container, dayId, activityId);
    } else if (activityAction === 'delete') {
      if (confirm('هل تريد حذف هذا النشاط؟')) {
        store.remove('activities', activityId);
        toast('تم حذف النشاط');
        renderItinerary(container);
      }
    } else if (activityAction === 'move-up') {
      moveActivity(dayId, activityId, 'up');
      renderItinerary(container);
    } else if (activityAction === 'move-down') {
      moveActivity(dayId, activityId, 'down');
      renderItinerary(container);
    }
  });
}

registerRoute('/itinerary', renderItinerary);
